dist: xenial
language: csharp
mono: none
dotnet: 2.2

install:
- dotnet restore GarbageCollectionApi/GarbageCollectionApi.csproj
- dotnet restore GarbageCollectionApi.UnitTests/GarbageCollectionApi.UnitTests.csproj
- dotnet restore GarbageCollectionApi.IntegrationTests/GarbageCollectionApi.IntegrationTests.csproj

jobs:
  include:
    - stage: build
      script: dotnet build GarbageCollectionApi/GarbageCollectionApi.csproj
    - stage: test
      script: test GarbageCollectionApi.UnitTests/GarbageCollectionApi.UnitTests.csproj
    - stage: test
      script: test GarbageCollectionApi.IntegrationTests/GarbageCollectionApi.IntegrationTests.csproj
